"""Judge-demo preflight for BorderGuard AI.

This script validates local demo prerequisites without generating or simulating
security events. It checks that the requested video exists and that the AI
engine configuration is readable.
"""
import argparse
from pathlib import Path

from config import BACKEND_API_BASE, BACKEND_AUTH_TOKEN, EVIDENCE_DIR


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--path", default="../media/videos/test.mp4")
    args = parser.parse_args()

    project_root = Path(__file__).resolve().parents[1]
    video = (Path(__file__).resolve().parent / args.path).resolve()
    evidence = Path(EVIDENCE_DIR).resolve()

    checks = [
        ("DEMO VIDEO", video.exists(), str(video)),
        ("BACKEND URL", bool(BACKEND_API_BASE), BACKEND_API_BASE),
        ("AI API TOKEN", bool(BACKEND_AUTH_TOKEN), "configured" if BACKEND_AUTH_TOKEN else "missing"),
        ("EVIDENCE DIR", evidence.exists() or evidence.parent.exists(), str(evidence)),
    ]

    print("\nBorderGuard AI — DEMO PREFLIGHT")
    print("No synthetic detections are generated by this check.\n")
    failed = False
    for name, ok, detail in checks:
        print(f"[{'PASS' if ok else 'FAIL'}] {name}: {detail}")
        failed |= not ok

    print("\nRecommended judge run:")
    print("  python video_processor.py --source video --path ../media/videos/test.mp4 --camera_id CAM-01 --demo --loop")
    print("\nExpected pipeline: DETECTION > TRACKING > ZONE > EVENT > RISK > ALERT > EVIDENCE")
    raise SystemExit(1 if failed else 0)


if __name__ == "__main__":
    main()
