# Generated by Django 5.0.6 on 2026-09-14 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=120)),
                ('sector', models.CharField(default='A', max_length=10)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('WARNING', 'Warning'), ('MAINTENANCE', 'Maintenance')], default='OFFLINE', max_length=20)),
                ('source_type', models.CharField(choices=[('UPLOAD', 'Uploaded Video'), ('WEBCAM', 'Webcam'), ('RTSP', 'RTSP / IP Camera')], default='UPLOAD', max_length=20)),
                ('source_path', models.CharField(blank=True, help_text='File path, webcam index, or RTSP URL', max_length=255)),
                ('ai_active', models.BooleanField(default=False)),
                ('fps', models.FloatField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='HIGH', max_length=20)),
                ('polygon', models.JSONField(default=list)),
                ('active_hours', models.CharField(default='24x7', max_length=40)),
                ('alert_threshold', models.CharField(default='1 person', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='surveillance.camera')),
            ],
        ),
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('person', 'Person'), ('vehicle', 'Vehicle')], max_length=20)),
                ('confidence', models.FloatField()),
                ('bbox', models.JSONField(help_text='[x1, y1, x2, y2] pixel coordinates')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='surveillance.camera')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveillance.zone')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('RESTRICTED_ZONE_INTRUSION', 'Restricted-zone intrusion'), ('PROLONGED_PRESENCE', 'Prolonged presence detected'), ('UNUSUAL_MOVEMENT', 'Unusual movement'), ('COMPOUND_INCIDENT', 'Compound incident'), ('NORMAL_DETECTION', 'Normal object detection')], max_length=40)),
                ('object_type', models.CharField(default='person', max_length=20)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20)),
                ('confidence', models.FloatField()),
                ('event_score', models.IntegerField(default=1, help_text='1-10 legacy priority score')),
                ('risk_score', models.IntegerField(default=0, help_text='0-100 contextual rule-based risk score')),
                ('risk_level', models.CharField(default='NORMAL', max_length=20)),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('track_id', models.CharField(blank=True, max_length=40)),
                ('dwell_seconds', models.FloatField(default=0)),
                ('movement_speed', models.FloatField(default=0)),
                ('correlation_id', models.CharField(blank=True, max_length=80)),
                ('correlated_alert_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('New', 'New'), ('Acknowledged', 'Acknowledged'), ('Investigating', 'Investigating'), ('Resolved', 'Resolved')], default='New', max_length=20)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='evidence/')),
                ('evidence_sha256', models.CharField(blank=True, max_length=64)),
                ('previous_evidence_hash', models.CharField(blank=True, max_length=64)),
                ('chain_hash', models.CharField(blank=True, max_length=64)),
                ('analyst_notes', models.TextField(blank=True)),
                ('reasoning', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=80)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='surveillance.camera')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveillance.zone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
